### ISSUE TITLE
Ort der Transitionen 

### ISSUE THREAD

**Issue by JLS666** [JLS666/spuelmaschine#10]
Wo sollen die Transitionen hin? Bis jetzt gibt es in der loop() ein Bereich extra für alle Transitionen. Mag für die Übersichtlichkeit gut sein, jedoch muss jedesmal eine if Abfrage durchgemacht werden, auch wenn man gar nicht im relevanten Zustand ist. Und die if-Abfragen sind sehr lang so. Ich fände es schöner, wenn die Transaktionen in dem Zustandsautomaten sind. Wie sieht ihr das?

**Comment by TrandyAndy** [comment]
Genau wir du. So 
in Loop übersichtlicher!
In Transition spart man sich genau eine Abfrage.

**Comment by JLS666** [comment]
Chef hat entschieden, dass die "globalen" Transitionen in die loop kommen, aber die lokalen in den update/do von dem Zustandsautomat.
