### ISSUE TITLE
Vorschlag: Variablen alle klein schreiben? 

### ISSUE THREAD

**Issue by JLS666** [JLS666/spuelmaschine#11]

**Comment by TrandyAndy** [comment]
Ich kenne mich nicht aus.
Aber eigentlich kein Problem da jeder nur seine Benutzt. und Aoutokorrektur an ist

**Comment by JLS666** [comment]
Ja ist eigentlich noch nicht wirklich nötig, aber bei großen Projekten wird das verwendet um Variablen von Klassen zu unterscheiden.

**Comment by JLS666** [comment]
Hallo Lockbuch: Der blanke Chaos ist ausgebrochen, Variablen werden gennant wie die Crew es will, mal groß mal klein, mal mit Bindestrick mal mit Underline. Schlimm Schlimm Schlimm. Aber da ist nicht's mehr zumachen, die Meutern sonst.
