### ISSUE TITLE
Da passiert ja nix

### ISSUE THREAD

**Issue by TrandyAndy** [JLS666/spuelmaschine#13]

**Comment by TrandyAndy** [comment]
Wann passiert denn was?

**Comment by TrandyAndy** [comment]
gleich passiert was

**Comment by TrandyAndy** [comment]
was passiert den hier

**Comment by TrandyAndy** [comment]
Ohne Till1 nicht so lustig

**Comment by JLS666** [comment]
Sei froh, sonst geht das Programm ja wieder nicht.

**Comment by JLS666** [comment]
Was hab ich gesagt?! Ich hab immer Recht!!!
