### ISSUE TITLE
DigitalWrite und read funktionen?

### ISSUE THREAD

**Issue by TrandyAndy** [JLS666/spuelmaschine#14]
ich weis das hat juli schon gefragt. Aber es ist doch schöner wenn Max nur KolbenRein() aufruft oder if(EndschalterHinten)  und es eine Funk oder Klasse gibt die das ganze Zeug mit Read, Pins und True false für hin löst. Oder meint Ihr nicht?

**Comment by JLS666** [comment]
Jop finde ich gut, aber bevor jetzt wild los programmiert wird, würde ich das erstmal dokumentieren.

**Comment by JLS666** [comment]
Aktueller Stand: Ohne Klasse nur mit Defines.
