### ISSUE TITLE
Musik

### ISSUE THREAD

**Issue by TrandyAndy** [JLS666/spuelmaschine#3]
@JLS666

**Comment by JLS666** [comment]
Wo stellt man denn die PWM ein?

**Comment by JLS666** [comment]
Vorschläge:

1. Das bisschen Haushalt

**Comment by TrandyAndy** [comment]
Hab ich hinzugefügt! mit setFrequenz.

2. lore lore
3. DE Hymne

**Comment by JLS666** [comment]
4. Das Loreleylied

**Comment by JLS666** [comment]
5. Es rappelt im Karton
