### ISSUE TITLE
Wohnort der Funktionen

### ISSUE THREAD

**Issue by JLS666** [JLS666/spuelmaschine#5]
Wo sollen wir die Funktionen hintun? In die main.cpp oder extra??

**Comment by TrandyAndy** [comment]
Welche funktion. Die Großen Sind als klassen da. Und sonnst ja main. Wenn es zu viel wird lässt sich das ja blitzschnell auslagern.

**Comment by JLS666** [comment]
Gemeinsame Meinung: Die main Funktionen auch auslagern, sonst zu voll!

**Comment by TrandyAndy** [comment]
Bin jetzt au dfür alle AKtionen und States raus zu lagern.

**Comment by JLS666** [comment]
Wenn das so einfach wäre.

**Comment by JLS666** [comment]
> Wenn es zu viel wird lässt sich das ja blitzschnell auslagern.

ROFL
