### ISSUE TITLE
Loop Time

### ISSUE THREAD

**Issue by TrandyAndy** [JLS666/spuelmaschine#7]
der LoopTime in main funktioniert nicht wie gedacht. Wiso?

**Comment by TrandyAndy** [comment]
wenn dus als Array hast kann ich es gerne Probieren

**Comment by JLS666** [comment]
Bin gerade dabei.

**Comment by JLS666** [comment]
Müsste oben sein, bin gespannt!
Du bekommst immer 100 Durchläufe auf einmal.

**Comment by JLS666** [comment]
Ergebnis: 30 bis 50 µs
