### ISSUE TITLE
Der Chef ist nicht da?!

### ISSUE THREAD

**Issue by JLS666** [JLS666/spuelmaschine#8]
Was sollen wir tun?

**Comment by TrandyAndy** [comment]
Wenn max da ist wird er uns den Weg weisen!

**Comment by JLS666** [comment]
Solange programmieren wir halt im Kreis. 🤷🏽‍♂️

**Comment by JLS666** [comment]
Chef ist endlich da! Programm geht halt nicht mehr. Aber sonst alles gut.
