### ISSUE TITLE
Welche Klasse oder was kümmert sich um die Endschalter abfrage?

### ISSUE THREAD

**Issue by JLS666** [JLS666/spuelmaschine#9]

**Comment by JLS666** [comment]
Eine Endschalter Klasse?

**Comment by TrandyAndy** [comment]
Wiso willst du die abfragen? Max kann doch einfach DigitalRead() schreiben und hat die. Das ist doch eine Arduiono klasse

**Comment by JLS666** [comment]
Meine Kernfrage, woher weiß mein Encoder, das der Endschalter erreicht wurde. Wer sagt das mir?
